#!/bin/bash --login
#PBS -l select=1
#PBS -l walltime=00:05:00
#PBS -A d59
  
cd $PBS_O_WORKDIR


module swap PrgEnv-cray PrgEnv-intel
export OMP_NUM_THREADS=24
export KMP_AFFINITY=verbose,disabled

#time aprun -n 1 -d $OMP_NUM_THREADS ../bin/postTimer.x ../implicit_examples/GLH_capped.xyz -k ../implicit_examples/GLH_capped.key 300 n 

time aprun -n 1 -d $OMP_NUM_THREADS -cc none ../bin/postTimer.x ../implicit_examples/3BDC_GK.xyz -k ../implicit_examples/3BDC_GK.key 50 n 
